// src/app/features/editor/components/sidebar/sidebar.component.ts
import { Component, Input, Output, EventEmitter, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { PageSummaryResponse } from '../../models/page.model';
import { UserResponse } from '../../../login/models/user.model';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './sidebar.component.html'
})
export class SidebarComponent {
  @Input() isOpen: boolean = true;
  @Input() pageSummaries: PageSummaryResponse[] = [];
  @Input() selectedPageId: string | null = null;
  @Input() searchQuery: string = '';
  @Input() currentUser: UserResponse | null = null;
  @Input() isDarkMode: boolean = false;
  @Input() isLoadingList: boolean = false;
  @Input() isCreating: boolean = false;
  @Input() isAdmin: boolean = false;

  @Output() selectPage = new EventEmitter<string>();
  @Output() deletePage = new EventEmitter<string>();
  @Output() createPage = new EventEmitter<void>();
  @Output() searchChange = new EventEmitter<string>();
  @Output() toggleTheme = new EventEmitter<void>();
  @Output() logout = new EventEmitter<void>();

  isDropdownOpen = signal<boolean>(false);

  userInitial = computed(() => {
    const user = this.currentUser;
    return user ? user.username.charAt(0).toUpperCase() : 'U';
  });

  toggleDropdown(): void {
    this.isDropdownOpen.update(open => !open);
  }

  handleCreateNew(): void {
    this.createPage.emit();
  }

  handleSelectPage(pageId: string): void {
    this.selectPage.emit(pageId);
  }

  handleDeletePage(event: Event, pageId: string): void {
    event.stopPropagation();
    if (confirm('Tem certeza que deseja apagar esta página?')) {
      this.deletePage.emit(pageId);
    }
  }

  handleSearchChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.searchChange.emit(input.value);
  }

  handleLogout(): void {
    this.logout.emit();
  }
}

<aside
  class="fixed left-0 top-0 z-40 h-screen w-80 border-r border-border bg-card transition-transform duration-300 ease-in-out"
  [ngClass]="{
    'translate-x-0': isOpen,
    '-translate-x-full': !isOpen
  }"
>
  <div class="flex h-full flex-col">
    <!-- Header -->
    <div class="border-b border-border/80 px-4 py-4">
      <div class="flex items-center justify-between gap-3">
        <div class="flex items-center gap-2">
          <i class="pi pi-book text-xl text-primary font-bold"></i>
          <span class="font-bold tracking-tight text-foreground">Noto</span>
        </div>

        <button
          (click)="handleCreateNew()"
          [disabled]="isCreating"
          size="sm"
          class="h-8 rounded-full px-3.5 bg-primary text-primary-foreground hover:bg-primary/95 text-xs font-semibold shadow-sm flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
        >
          <i class="pi pi-plus text-xs"></i>
          <span>{{ isCreating ? 'Criando...' : 'Novo' }}</span>
        </button>
      </div>

      <!-- Barra de Busca -->
      <div class="relative mt-4">
        <i class="pi pi-search absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-xs"></i>
        <input
          [value]="searchQuery"
          (input)="handleSearchChange($event)"
          type="text"
          placeholder="Buscar por título..."
          class="w-full h-9 pl-9 pr-4 text-xs rounded-lg border border-border/60 bg-background text-foreground focus:ring-1 focus:ring-primary/40 focus:outline-none"
        />
      </div>
    </div>

    <!-- Lista de Anotações -->
    <div class="flex-1 overflow-y-auto p-3 space-y-1">
      @if (isLoadingList) {
        <div class="space-y-3 p-2">
          <div class="h-8 bg-muted/40 rounded-lg animate-pulse"></div>
          <div class="h-8 bg-muted/40 rounded-lg animate-pulse w-3/4"></div>
          <div class="h-8 bg-muted/40 rounded-lg animate-pulse w-5/6"></div>
        </div>
      } @else if (pageSummaries.length === 0) {
        <div class="text-center py-8">
          <p class="text-xs text-muted-foreground italic">Nenhuma página encontrada</p>
        </div>
      } @else {
        @for (page of pageSummaries; track page.id) {
          <div
            (click)="handleSelectPage(page.id)"
            class="group flex items-center justify-between px-3 py-2.5 rounded-lg text-sm font-medium transition-all duration-200 cursor-pointer"
            [ngClass]="{
              'bg-primary/10 text-primary border border-primary/20': selectedPageId === page.id,
              'hover:bg-primary/5 text-muted-foreground border border-transparent': selectedPageId !== page.id
            }"
          >
            <div class="flex-1 truncate mr-2">
              <p class="truncate font-semibold" [ngClass]="{ 'text-primary': selectedPageId === page.id, 'text-foreground': selectedPageId !== page.id }">
                {{ page.title || 'Sem título' }}
              </p>
              <p class="text-[10px] text-muted-foreground mt-0.5 font-light">
                {{ page.updatedAt | date: 'dd/MM/yyyy HH:mm' }}
              </p>
            </div>

            <!-- Botão Excluir que aparece no Hover -->
            <button
              (click)="handleDeletePage($event, page.id)"
              class="opacity-0 group-hover:opacity-100 hover:text-red-500 p-1 rounded transition-opacity duration-200 focus:opacity-100 cursor-pointer"
              aria-label="Apagar nota"
            >
              <i class="pi pi-trash text-xs"></i>
            </button>
          </div>
        }
      }
    </div>

    <!-- Rodapé e Menu de Perfil -->
    <div class="border-t border-border/80 px-4 py-3 relative">
      <!-- Dropdown Popup de Perfil -->
      @if (isDropdownOpen()) {
        <div
          class="absolute bottom-16 left-4 z-[50] w-64 rounded-xl border border-border bg-card shadow-2xl p-2 flex flex-col space-y-1 animate-fade-in"
        >
          <div class="px-2 py-2 border-b border-border mb-1 text-xs">
            <p class="font-bold truncate text-foreground">{{ currentUser?.username }}</p>
            <p class="text-[10px] text-muted-foreground truncate">{{ currentUser?.email }}</p>
          </div>

          <a
            routerLink="/settings"
            (click)="isDropdownOpen.set(false)"
            class="flex items-center gap-2 px-2 py-2 rounded-lg text-xs font-semibold hover:bg-primary/10 text-foreground transition-colors cursor-pointer"
          >
            <i class="pi pi-cog"></i>
            <span>Configurações</span>
          </a>

          <a
            routerLink="/media"
            (click)="isDropdownOpen.set(false)"
            class="flex items-center gap-2 px-2 py-2 rounded-lg text-xs font-semibold hover:bg-primary/10 text-foreground transition-colors cursor-pointer"
          >
            <i class="pi pi-image"></i>
            <span>Galeria</span>
          </a>

          @if (isAdmin) {
            <a
              routerLink="/admin"
              (click)="isDropdownOpen.set(false)"
              class="flex items-center gap-2 px-2 py-2 rounded-lg text-xs font-semibold hover:bg-primary/10 text-foreground transition-colors cursor-pointer"
            >
              <i class="pi pi-shield"></i>
              <span>Administração</span>
            </a>
          }
        </div>
      }

      <div class="flex items-center justify-between">
        <!-- Gatilho do Menu de Conta -->
        <button
          (click)="toggleDropdown()"
          class="flex items-center justify-center h-10 w-10 rounded-full border border-border bg-background cursor-pointer hover:border-primary/40 focus:outline-none transition-colors"
          aria-label="Opções de conta"
        >
          @if (currentUser?.profileImageUrl) {
            <img
              [src]="currentUser?.profileImageUrl"
              alt="Foto do usuário"
              class="h-full w-full rounded-full object-cover"
            />
          } @else {
            <div class="h-full w-full rounded-full bg-primary/10 text-primary font-bold flex items-center justify-center text-sm">
              {{ userInitial() }}
            </div>
          }
        </button>

        <div class="flex items-center gap-1.5">
          <!-- Toggle Dark Mode -->
          <button
            (click)="toggleTheme.emit()"
            class="p-2 rounded-lg hover:bg-primary/10 text-muted-foreground hover:text-primary transition-colors cursor-pointer"
            aria-label="Alternar tema"
          >
            <i [class]="isDarkMode ? 'pi pi-sun text-sm' : 'pi pi-moon text-sm'"></i>
          </button>

          <!-- Logout -->
          <button
            (click)="handleLogout()"
            class="p-2 rounded-lg hover:bg-red-500/10 text-muted-foreground hover:text-red-500 transition-colors cursor-pointer"
            aria-label="Sair"
          >
            <i class="pi pi-power-off text-sm"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
</aside>

// components/layout/Sidebar.tsx
"use client";

import { PageList } from "@/components/pages/PageList";
import { PageListSkeleton } from "@/components/skeletons/PageListSkeleton";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Sheet, SheetContent } from "@/components/ui/sheet";
import { useAuth } from "@/contexts/AuthContext";
import { useNotes } from "@/contexts/NotesContext";
import { useSidebar } from "@/contexts/SidebarContext";
import { useTheme } from "@/contexts/ThemeContext";
import { useMobile } from "@/hooks/useMobile";
import { cn } from "@/lib/utils";
import { BookOpen, Image as ImageIcon, LogOut, Moon, Plus, Search, Settings, Shield, Sun } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useRef } from "react";

interface SidebarPanelProps {
  isMobileLayout: boolean;
}

function SidebarPanel({ isMobileLayout }: SidebarPanelProps) {
  const {
    createNewPage,
    isLoadingList,
    isCreating,
    filteredPageSummaries,
    searchQuery,
    setSearchQuery,
  } = useNotes();
  const { closeSidebar } = useSidebar();
  const { user, logout } = useAuth();
  const { darkMode, toggleDarkMode } = useTheme();

  const isAdmin = user?.roles?.includes("ROLE_ADMIN") ?? false;
  const userInitial = useMemo(
    () => user?.username?.charAt(0).toUpperCase() || "U",
    [user?.username]
  );

  const closeAfterAction = () => {
    if (isMobileLayout) {
      closeSidebar();
    }
  };

  const handleCreateNew = async () => {
    await createNewPage();
    closeAfterAction();
  };

  const handleThemeToggle = () => {
    toggleDarkMode();
    closeAfterAction();
  };

  const handleLogout = () => {
    closeAfterAction();
    logout();
  };

  return (
    <div className="flex h-full flex-col bg-background">
      <div className="border-b border-border px-4 py-4">
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <BookOpen className="h-5 w-5 text-primary" />
            <span className="font-semibold tracking-tight">Noto</span>
          </div>

          <Button
            onClick={handleCreateNew}
            size="sm"
            className="px-3"
            disabled={isCreating}
          >
            <Plus className="mr-1 h-4 w-4" />
            {isCreating ? "Criando..." : "Novo"}
          </Button>
        </div>

        <div className="relative mt-3">
          <Search className="pointer-events-none absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={searchQuery}
            onChange={(event) => setSearchQuery(event.target.value)}
            placeholder="Buscar por titulo, data ou hora"
            className="h-9 pl-8"
          />
        </div>
      </div>

      <ScrollArea className="flex-1 overflow-y-auto">
        <div className="p-3">
          {isLoadingList ? (
            <PageListSkeleton />
          ) : (
            <PageList
              pages={filteredPageSummaries}
              onPageSelect={isMobileLayout ? closeSidebar : undefined}
            />
          )}
        </div>
      </ScrollArea>

      <div className="border-t border-border px-3 py-3">
        <div className="flex items-center justify-between">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-10 w-10 rounded-full p-0"
                aria-label="Abrir menu de conta"
              >
                <Avatar className="h-10 w-10">
                  <AvatarImage
                    src={user?.profileImageUrl || undefined}
                    alt={user?.username || "Usuário"}
                  />
                  <AvatarFallback className="bg-primary/15 text-primary font-semibold">
                    {userInitial}
                  </AvatarFallback>
                </Avatar>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start" side="top" className="w-56">
              <div className="px-2 py-1.5">
                <p className="truncate text-sm font-medium">{user?.username || "Usuário"}</p>
                <p className="truncate text-xs text-muted-foreground">{user?.email || "-"}</p>
              </div>
              <DropdownMenuItem asChild>
                <Link href="/settings" onClick={closeAfterAction}>
                  <Settings className="mr-2 h-4 w-4" />
                  <span>Configurações</span>
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem asChild>
                <Link href="/media" onClick={closeAfterAction}>
                  <ImageIcon className="mr-2 h-4 w-4" />
                  <span>Galeria</span>
                </Link>
              </DropdownMenuItem>
              {isAdmin && (
                <DropdownMenuItem asChild>
                  <Link href="/admin" onClick={closeAfterAction}>
                    <Shield className="mr-2 h-4 w-4" />
                    <span>Administração</span>
                  </Link>
                </DropdownMenuItem>
              )}
            </DropdownMenuContent>
          </DropdownMenu>

          <div className="flex items-center gap-1">
            <Button
              variant="ghost"
              size="icon"
              onClick={handleThemeToggle}
              aria-label={darkMode ? "Ativar modo claro" : "Ativar modo escuro"}
            >
              {darkMode ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
            </Button>
            <Button
              variant="ghost"
              size="icon"
              className="text-red-600 hover:text-red-600"
              onClick={handleLogout}
              aria-label="Sair"
            >
              <LogOut className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

export function Sidebar() {
  const { isSidebarOpen, setSidebarOpen, closeSidebar } = useSidebar();
  const isMobile = useMobile();
  const desktopDrawerRef = useRef<HTMLElement>(null);

  useEffect(() => {
    if (isMobile || !isSidebarOpen) {
      return;
    }

    const handleOutsideClick = (event: MouseEvent) => {
      const target = event.target as Node;
      if (desktopDrawerRef.current?.contains(target)) {
        return;
      }

      const toggleButton = document.querySelector('[data-sidebar-toggle="true"]');
      if (toggleButton?.contains(target)) {
        return;
      }

      closeSidebar();
    };

    document.addEventListener("mousedown", handleOutsideClick);
    return () => document.removeEventListener("mousedown", handleOutsideClick);
  }, [isMobile, isSidebarOpen, closeSidebar]);

  if (isMobile) {
    return (
      <Sheet open={isSidebarOpen} onOpenChange={setSidebarOpen}>
        <SheetContent side="left" className="w-80 p-0 [&>button]:hidden">
          <SidebarPanel isMobileLayout />
        </SheetContent>
      </Sheet>
    );
  }

  return (
    <aside
      ref={desktopDrawerRef}
      className={cn(
        "fixed left-0 top-0 z-40 h-screen w-80 border-r border-border bg-background transition-transform duration-300 ease-in-out",
        isSidebarOpen ? "translate-x-0" : "-translate-x-full"
      )}
    >
      <SidebarPanel isMobileLayout={false} />
    </aside>
  );
}
