// components/notes/NoteEditor.tsx
"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useNotes } from "@/contexts/NotesContext";
import { parseMarkdown } from "@/lib/markdownParser";
import { uploadMedia } from "@/lib/media";
/**
 * NOTO - Note Editor Component (v2.0 - CodeMirror 6 Migration)
 * -----------------------------------------------------------
 * Este componente é o coração da edição no Noto. Ele utiliza o CodeMirror 6
 * como motor principal para garantir performance, conformidade com CommonMark
 * e uma experiência de escrita "premium".
 * 
 * ARQUITETURA E FLUXO:
 * 
 * 1. MOTOR (CodeMirror 6):
 *    - O editor é inicializado via `useEffect` no container `editorRef`.
 *    - Utilizamos `EditorView` para o DOM e `EditorState` para a lógica.
 *    - Extensões principais: history (undo/redo), markdown (CommonMark), 
 *      syntaxHighlighting (estilo customizado) e o tema One Dark adaptado.
 * 
 * 2. SINCRONIZAÇÃO DE ESTADO:
 *    - Bidirecional: 
 *      a) Editor -> Contexto: O `updateListener` detecta mudanças no doc e chama `handleContentChange`.
 *      b) Contexto -> Editor: Um `useEffect` observa `editContent` (ex: ao carregar uma nota) 
 *         e despacha uma transação de mudança se o conteúdo divergir.
 * 
 * 3. SCROLL SINCRONIZADO (Bidirecional):
 *    - O scroll é baseado em porcentagem relativa.
 *    - `scrollSourceRef` e `previewModeRef` são usados para evitar loops infinitos 
 *      de eventos quando um lado "empurra" o scroll do outro.
 *    - O editor permanece montado (mesmo que oculto) para preservar estado e foco.
 * 
 * 4. BARRA DE FERRAMENTAS E ATALHOS:
 *    - Utilizamos uma "Ponte de Comandos": A UI (Shadcn) e o `keymap` chamam as 
 *      mesmas funções (`insertBold`, `insertH1`, etc).
 *    - Estas funções usam `view.dispatch()` para manipular o texto via transações, 
 *      garantindo que o histórico de Undo/Redo funcione perfeitamente.
 * 
 * 5. DESIGN (Pure Black):
 *    - O tema é dinâmico via `next-themes`.
 *    - No modo escuro, forçamos `backgroundColor: transparent` para herdar o 
 *      preto absoluto (#000000) da aplicação, otimizando o contraste.
 * 
 * 6. MULTIMÍDIA:
 *    - O `handlePaste` intercepta imagens do clipboard e faz o upload automático,
 *      inserindo o link Markdown no local exato do cursor.
 */

import {
  Bold,
  Code,
  Edit3,
  Eye,
  EyeOff,
  Heading1,
  Heading2,
  Heading3,
  Image,
  Italic,
  Link,
  List,
  ListOrdered,
  Maximize2,
  Minimize2,
  Quote,
  Save,
} from "lucide-react";
import { useCallback, useEffect, useRef, useState, useMemo } from "react";
import { useDebouncedCallback } from "@/hooks/useDebouncedCallback";
import { toast } from "sonner";
import { useTheme } from "next-themes";

// CodeMirror imports
import { EditorState, Transaction, EditorSelection } from "@codemirror/state";
import { EditorView, keymap, highlightActiveLine, scrollPastEnd } from "@codemirror/view";
import { defaultKeymap, history, historyKeymap, undo as cmUndo, redo as cmRedo } from "@codemirror/commands";
import { markdown, commonmarkLanguage } from "@codemirror/lang-markdown";
import { languages } from "@codemirror/language-data";
import { syntaxHighlighting, defaultHighlightStyle, HighlightStyle, syntaxHighlighting as createSyntaxHighlighting } from "@codemirror/language";
import { oneDark } from "@codemirror/theme-one-dark";
import { tags as t } from "@lezer/highlight";

// Função utilitária fora do componente para evitar que o React Compiler 
// reclame de mutação direta de DOM em refs.
const performScrollSync = (
  source: "editor" | "preview",
  editorScrollDOM: HTMLElement,
  previewDOM: HTMLElement
) => {
  if (source === "editor") {
    const scrollPercentage = editorScrollDOM.scrollTop / (editorScrollDOM.scrollHeight - editorScrollDOM.clientHeight);
    previewDOM.scrollTop = scrollPercentage * (previewDOM.scrollHeight - previewDOM.clientHeight);
  } else {
    const scrollPercentage = previewDOM.scrollTop / (previewDOM.scrollHeight - previewDOM.clientHeight);
    editorScrollDOM.scrollTop = scrollPercentage * (editorScrollDOM.scrollHeight - editorScrollDOM.clientHeight);
  }
};

export function NoteEditor() {
  const {
    editTitle,
    editContent,
    handleTitleChange,
    handleContentChange,
    autoSavePage,
    hasUnsavedChanges,
    isSaving,
  } = useNotes();

  // Estado com localStorage para persistir o modo preferido
  const [previewMode, setPreviewMode] = useState<"edit" | "preview" | "split">(
    () => {
      if (typeof window !== "undefined") {
        return (
          (localStorage.getItem("noteEditorMode") as
            | "edit"
            | "preview"
            | "split") || "edit"
        );
      }
      return "edit";
    }
  );
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isUploadingImage, setIsUploadingImage] = useState(false);
  const previewRef = useRef<HTMLDivElement>(null);
  const scrollSourceRef = useRef<"editor" | "preview" | null>(null);
  const editContentRef = useRef(editContent);

  useEffect(() => {
    editContentRef.current = editContent;
  }, [editContent]);

  // Salvar no localStorage quando o modo mudar
  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("noteEditorMode", previewMode);
    }
  }, [previewMode]);

  const [isAutoSaveEnabled, setIsAutoSaveEnabled] = useState<boolean>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("noteAutoSave");
      return saved !== null ? saved === "true" : true;
    }
    return true;
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("noteAutoSave", isAutoSaveEnabled.toString());
    }
  }, [isAutoSaveEnabled]);

  const { resolvedTheme } = useTheme();

  // Refs para sincronização de estado sem causar re-render do editor
  const previewModeRef = useRef(previewMode);
  useEffect(() => {
    previewModeRef.current = previewMode;
  }, [previewMode]);

  // Auto-save usando um custom hook
  const debouncedAutoSave = useDebouncedCallback(() => {
    if (hasUnsavedChanges && isAutoSaveEnabled) {
      autoSavePage();
    }
  }, 2000);

  useEffect(() => {
    if (hasUnsavedChanges && isAutoSaveEnabled) {
      debouncedAutoSave();
    }
  }, [editContent, editTitle, hasUnsavedChanges, isAutoSaveEnabled, debouncedAutoSave]);

  // Refs para o CodeMirror
  const editorRef = useRef<HTMLDivElement>(null);
  const viewRef = useRef<EditorView | null>(null);

  // Funções de Undo/Redo usando CodeMirror
  const undo = useCallback(() => {
    if (viewRef.current) {
      cmUndo(viewRef.current);
    }
  }, []);

  const redo = useCallback(() => {
    if (viewRef.current) {
      cmRedo(viewRef.current);
    }
  }, []);

  // Função para inserir texto no CodeMirror
  const insertTextAtCursor = (
    beforeText: string,
    afterText: string = "",
    selectText: boolean = false
  ) => {
    if (!viewRef.current) return;

    const view = viewRef.current;
    const { state, dispatch } = view;
    
    const changes = state.changeByRange((range) => {
      const selectedText = state.sliceDoc(range.from, range.to);
      const insertion = selectText && selectedText
        ? beforeText + selectedText + afterText
        : beforeText + afterText;
        
      return {
        range: EditorSelection.cursor(range.from + beforeText.length + (selectText && selectedText ? selectedText.length : 0)),
        changes: { from: range.from, to: range.to, insert: insertion }
      };
    });

    dispatch(state.update(changes, { scrollIntoView: true, userEvent: "input" }));
    view.focus();
  };

  // Funções para formatação
  const insertBold = () => insertTextAtCursor("**", "**", true);
  const insertItalic = () => insertTextAtCursor("*", "*", true);
  const insertH1 = () => insertTextAtCursor("# ", "");
  const insertH2 = () => insertTextAtCursor("## ", "");
  const insertH3 = () => insertTextAtCursor("### ", "");
  const insertCode = () => insertTextAtCursor("`", "`", true);
  const insertQuote = () => insertTextAtCursor("> ", "");
  const insertList = () => insertTextAtCursor("- ", "");
  const insertOrderedList = () => insertTextAtCursor("1. ", "");
  const insertLink = () => insertTextAtCursor("[", "](url)");

  const getImageFileFromClipboard = useCallback((e: ClipboardEvent) => {
    const items = e.clipboardData?.items;
    if (!items) {
      return null;
    }

    for (const item of items) {
      if (item.kind === "file" && item.type.startsWith("image/")) {
        const file = item.getAsFile();
        if (file) {
          return file;
        }
      }
    }

    return null;
  }, []);

  // Interceptor de Ctrl+V para upload de imagens
  const handlePaste = async (e: ClipboardEvent) => {
    const imageFile = getImageFileFromClipboard(e);
    if (!imageFile) {
      return;
    }

    e.preventDefault();

    if (isUploadingImage) {
      return;
    }

    setIsUploadingImage(true);
    const uploadToastId = toast.loading("Enviando imagem...");

    try {
      const mediaResponse = await uploadMedia(imageFile);
      insertTextAtCursor(mediaResponse.markdown, "");
      toast.success("Imagem enviada com sucesso", { id: uploadToastId });
    } catch {
      toast.error("Erro ao enviar imagem. Tente novamente.", {
        id: uploadToastId,
      });
    } finally {
      setIsUploadingImage(false);
    }
  };

    // Função para sincronizar o scroll no modo split (Bidirecional)
  const handleScroll = (source: "editor" | "preview") => {
    if (previewModeRef.current !== "split" || !previewRef.current || !viewRef.current) return;

    // Se o scroll foi disparado programaticamente por uma sincronização, ignora para evitar loop infinito
    if (scrollSourceRef.current && scrollSourceRef.current !== source) {
      scrollSourceRef.current = null; 
      return;
    }

    scrollSourceRef.current = source;
    
    // Obter o elemento de scroll do CodeMirror
    const editorScrollDOM = viewRef.current.scrollDOM;
    
    // Executar a sincronia via função externa para não irritar o React Compiler
    performScrollSync(source, editorScrollDOM, previewRef.current);

    setTimeout(() => {
      if (scrollSourceRef.current === source) {
        scrollSourceRef.current = null;
      }
    }, 50);
  };


  // Inicialização do CodeMirror
  useEffect(() => {
    if (!editorRef.current) return;

    // Estilo customizado para links e tarefas (mais legível no dark mode)
    const customHighlightStyle = HighlightStyle.define([
      { tag: t.link, color: resolvedTheme === "dark" ? "#61afef" : "#0969da", textDecoration: "underline" },
      { tag: t.url, color: resolvedTheme === "dark" ? "#abb2bf" : "#57606a", opacity: 0.7 },
      { tag: t.heading1, fontWeight: "bold", fontSize: "1.4em", color: resolvedTheme === "dark" ? "#e06c75" : "#cf222e" },
      { tag: t.heading2, fontWeight: "bold", fontSize: "1.2em", color: resolvedTheme === "dark" ? "#d19a66" : "#953800" },
      { tag: t.strikethrough, textDecoration: "line-through" },
      { tag: t.meta, color: resolvedTheme === "dark" ? "#c678dd" : "#8250df" }, // Tasks [-] [x]
    ]);

    const startState = EditorState.create({
      doc: editContent,
      extensions: [
        history(),
        keymap.of([
          { key: "Mod-b", run: () => { insertBold(); return true; } },
          { key: "Mod-i", run: () => { insertItalic(); return true; } },
          { key: "Mod-k", run: () => { insertLink(); return true; } },
          { key: "Mod-1", run: () => { insertH1(); return true; } },
          { key: "Mod-2", run: () => { insertH2(); return true; } },
          { key: "Mod-3", run: () => { insertH3(); return true; } },
          { key: "Mod-l", run: () => { insertList(); return true; } },
          { key: "Mod-Shift-l", run: () => { insertOrderedList(); return true; } },
          ...defaultKeymap,
          ...historyKeymap,
        ]),
        markdown({
          base: commonmarkLanguage,
          codeLanguages: languages,
          addKeymap: true // Ativa atalhos de markdown como listas automáticas
        }),
        createSyntaxHighlighting(customHighlightStyle),
        resolvedTheme === "dark" ? oneDark : [],
        highlightActiveLine(),
        scrollPastEnd(),
        EditorView.lineWrapping,
        EditorView.theme({
          "&": {
            height: "100%",
            fontSize: "16px",
            backgroundColor: "transparent !important",
          },
          "&.cm-focused": {
            outline: "none",
          },
          ".cm-content": {
            padding: "20px",
            fontFamily: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
          },
          ".cm-scroller": {
            lineHeight: "1.6",
            backgroundColor: "transparent !important",
          },
          ".cm-gutters": {
            backgroundColor: "transparent !important",
            border: "none",
            color: resolvedTheme === "dark" ? "#4b5263" : "#9ca3af",
          },
          ".cm-activeLine": {
            backgroundColor: resolvedTheme === "dark" ? "rgba(255, 255, 255, 0.05) !important" : "rgba(0, 0, 0, 0.03) !important",
          },
          ".cm-activeLineGutter": {
            backgroundColor: "transparent !important",
            color: resolvedTheme === "dark" ? "#e06c75" : "#cf222e",
          },
          ".cm-selectionBackground, .cm-content ::selection": {
            backgroundColor: resolvedTheme === "dark" ? "rgba(255, 255, 255, 0.2) !important" : "rgba(0, 0, 0, 0.1) !important",
          }
        }, { dark: resolvedTheme === "dark" }),
        EditorView.updateListener.of((update) => {
          if (update.docChanged) {
            handleContentChange(update.state.doc.toString());
          }
        }),
        // Handler de eventos do DOM
        EditorView.domEventHandlers({
          scroll: () => {
            // Usamos a Ref para evitar stale closure
            if (previewModeRef.current === "split") {
              handleScroll("editor");
            }
          },
          paste: (event) => {
            handlePaste(event);
          }
        })
      ],
    });

    const view = new EditorView({
      state: startState,
      parent: editorRef.current,
    });

    viewRef.current = view;

    return () => {
      view.destroy();
    };
  }, [resolvedTheme]); // Re-inicializa apenas quando o tema muda para aplicar as cores corretamente

  // Sincronizar conteúdo de fora para dentro (ex: quando carrega uma nota)
  useEffect(() => {
    if (viewRef.current && editContent !== viewRef.current.state.doc.toString()) {
      viewRef.current.dispatch({
        changes: { from: 0, to: viewRef.current.state.doc.length, insert: editContent }
      });
    }
  }, [editContent]);



  const handleContentClick = (e: React.MouseEvent) => {
    const target = e.target as HTMLElement;
    const imgContainer = target.closest('.markdown-img-container') as HTMLElement;
    
    if (imgContainer) {
      const src = imgContainer.getAttribute('data-image-src');
      const alt = imgContainer.getAttribute('data-image-alt');
      
      if (src && window.openImageModal) {
        window.openImageModal(src, alt || '');
      }
    }
  };

  // Auto-focus no editor quando entra em modo de edição
  useEffect(() => {
    if (viewRef.current) {
      viewRef.current.focus();
    }
  }, []);

  // Atalhos de teclado (P e Fullscreen apenas, o resto o CM resolve)
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // Ctrl/Cmd + P para alternar preview
      if ((e.ctrlKey || e.metaKey) && e.key === "p") {
        e.preventDefault();
        const modes: Array<"edit" | "preview" | "split"> = [
          "edit",
          "split",
          "preview",
        ];
        const currentIndex = modes.indexOf(previewMode);
        const nextMode = modes[(currentIndex + 1) % modes.length];
        setPreviewMode(nextMode);
      }

      // Ctrl/Cmd + Shift + F para fullscreen
      if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === "F") {
        e.preventDefault();
        setIsFullscreen(!isFullscreen);
      }
    };

    document.addEventListener("keydown", handleKeyDown);

    return () => {
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [
    previewMode,
    isFullscreen
  ]);

  const renderSaveStatus = () => {
    if (isSaving) {
      return (
        <>
          <span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse" />
          Salvando...
        </>
      );
    }

    if (hasUnsavedChanges) {
      return (
        <>
          <span className="w-2 h-2 rounded-full bg-muted-foreground" />
          Editando...
        </>
      );
    }

    return (
      <>
        <span className="w-2 h-2 rounded-full bg-emerald-500" />
        Salvo
      </>
    );
  };

  return (
    <div
      className={`transition-all duration-300 opacity-100 translate-y-0 ${
        isFullscreen ? "fixed inset-0 z-50 bg-background" : ""
      }`}
    >
      <div
        className={`${
          isFullscreen ? "h-full p-4" : "max-w-7xl mx-auto p-4 md:p-8"
        }`}
      >
        {/* Header com título */}
        <div className="mb-6">
          <Input
            value={editTitle}
            onChange={(e) => handleTitleChange(e.target.value)}
            placeholder="Título da entrada..."
            className="text-2xl md:text-4xl font-bold border-none p-0 mb-4 bg-transparent focus-visible:ring-0 focus-visible:ring-offset-0"
          />

          {/* Barra de ferramentas */}
          <div className="flex items-center gap-2 mb-4 p-2 border rounded-lg bg-muted/50">
            <Button
              variant={previewMode === "edit" ? "default" : "ghost"}
              size="sm"
              onClick={() => setPreviewMode("edit")}
              className="flex items-center gap-2"
            >
              <Edit3 className="w-4 h-4" />
              Editor
            </Button>

            <Button
              variant={previewMode === "preview" ? "default" : "ghost"}
              size="sm"
              onClick={() => setPreviewMode("preview")}
              className="flex items-center gap-2"
            >
              <EyeOff className="w-4 h-4" />
              Preview
            </Button>

            <Button
              variant={previewMode === "split" ? "default" : "ghost"}
              size="sm"
              onClick={() => setPreviewMode("split")}
              className="flex items-center gap-2"
            >
              <Eye className="w-4 h-4" />
              Split
            </Button>

            <div className="ml-auto flex items-center gap-4">
              <span className="text-sm text-muted-foreground flex items-center gap-2">
                {renderSaveStatus()}
              </span>
              <Button
                variant={isAutoSaveEnabled ? "outline" : "secondary"}
                size="sm"
                onClick={() => setIsAutoSaveEnabled(!isAutoSaveEnabled)}
                className="flex items-center gap-2"
                title="Alternar Auto-Save"
              >
                <Save className="w-4 h-4" />
                {isAutoSaveEnabled ? "Auto-Save: ON" : "Auto-Save: OFF"}
              </Button>
              {!isAutoSaveEnabled && hasUnsavedChanges && (
                <Button
                  variant="default"
                  size="sm"
                  onClick={() => autoSavePage()}
                  className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white"
                >
                  <Save className="w-4 h-4" />
                  Salvar
                </Button>
              )}
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setIsFullscreen(!isFullscreen)}
                className="flex items-center gap-2"
              >
                {isFullscreen ? (
                  <Minimize2 className="w-4 h-4" />
                ) : (
                  <Maximize2 className="w-4 h-4" />
                )}
                {isFullscreen ? "Sair" : "Fullscreen"}
              </Button>
            </div>
          </div>
        </div>

        {/* Barra de formatação */}
        {(previewMode === "edit" || previewMode === "split") && (
          <div className="flex flex-wrap items-center gap-1 p-2 mb-2 border rounded-lg bg-muted/30">
            <Button
              variant="ghost"
              size="sm"
              onClick={insertBold}
              title="Bold (Ctrl+B)"
            >
              <Bold className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={insertItalic}
              title="Italic (Ctrl+I)"
            >
              <Italic className="w-4 h-4" />
            </Button>
            <div className="w-px h-6 bg-border mx-1" />
            <Button
              variant="ghost"
              size="sm"
              onClick={insertH1}
              title="Heading 1"
            >
              <Heading1 className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={insertH2}
              title="Heading 2"
            >
              <Heading2 className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={insertH3}
              title="Heading 3"
            >
              <Heading3 className="w-4 h-4" />
            </Button>
            <div className="w-px h-6 bg-border mx-1" />
            <Button
              variant="ghost"
              size="sm"
              onClick={insertList}
              title="Lista"
            >
              <List className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={insertOrderedList}
              title="Lista numerada"
            >
              <ListOrdered className="w-4 h-4" />
            </Button>
            <div className="w-px h-6 bg-border mx-1" />
            <Button
              variant="ghost"
              size="sm"
              onClick={insertQuote}
              title="Citação"
            >
              <Quote className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={insertCode}
              title="Código"
            >
              <Code className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={insertLink}
              title="Link (Ctrl+K)"
            >
              <Link className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => insertTextAtCursor("![Alt text](", ")")}
              title="Imagem"
            >
              <Image className="w-4 h-4" />
            </Button>
          </div>
        )}

        {/* Área do Editor */}
        <div
          className={`border rounded-lg overflow-hidden flex ${
            isFullscreen
              ? "h-[calc(100vh-300px)]"
              : "h-[calc(100vh-320px)] min-h-[700px]"
          }`}
        >
          {/* Editor (Sempre montado para não perder estado/foco) */}
          <div 
            ref={editorRef} 
            className={`flex-1 bg-background relative overflow-hidden ${
              previewMode === "preview" ? "hidden" : "block"
            }`}
          />

          {/* Divisor vertical no modo Split */}
          {previewMode === "split" && (
            <div className="w-px bg-border flex-shrink-0" />
          )}

          {/* Preview */}
          <div 
            ref={previewRef}
            onScroll={() => handleScroll("preview")}
            className={`flex-1 bg-background overflow-y-auto relative ${
              previewMode === "edit" ? "hidden" : "block"
            }`}
          >
            <div
              className={`p-6 prose prose-neutral dark:prose-invert max-w-none ${
                previewMode === "split" ? "prose-sm" : "prose-base"
              }`}
              dangerouslySetInnerHTML={{
                __html: editContent
                  ? parseMarkdown(editContent)
                  : `<p class='text-muted-foreground italic'>${
                      previewMode === "split" 
                        ? "Preview aparecerá aqui..." 
                        : "Preview aparecerá aqui quando você escrever algo..."
                    }</p>`,
              }}
              onClick={handleContentClick}
            />
          </div>
        </div>

        {/* Dicas de atalhos */}
        {/* <div className="mt-4 p-3 bg-muted/30 rounded-lg">
          <p className="text-xs text-muted-foreground">
            💡 <strong>Atalhos:</strong>
            <span className="mx-2">Ctrl+Z desfazer</span>
            <span className="mx-2">Ctrl+Y refazer</span>
            <span className="mx-2">Ctrl+B bold</span>
            <span className="mx-2">Ctrl+I italic</span>
            <span className="mx-2">Ctrl+K link</span>
            <span className="mx-2">
              Enter em listas = continua automaticamente
            </span>
          </p>
        </div> */}
      </div>
    </div>
  );
}

// src/app/features/editor/components/note-editor/note-editor.component.ts
import { Component, Input, Output, EventEmitter, signal, effect, ElementRef, ViewChild, AfterViewInit, OnDestroy, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MarkdownPipe } from '../../../../shared/pipes/markdown.pipe';
import { Subject, debounceTime, takeUntil } from 'rxjs';

// CodeMirror Core
import { EditorState, EditorSelection } from '@codemirror/state';
import { EditorView, keymap, highlightActiveLine, scrollPastEnd } from '@codemirror/view';
import { defaultKeymap, history, historyKeymap, undo as cmUndo, redo as cmRedo } from '@codemirror/commands';
import { markdown, commonmarkLanguage } from '@codemirror/lang-markdown';
import { syntaxHighlighting, HighlightStyle } from '@codemirror/language';
import { oneDark } from '@codemirror/theme-one-dark';
import { tags as t } from '@lezer/highlight';

@Component({
  selector: 'app-note-editor',
  standalone: true,
  imports: [CommonModule, FormsModule, MarkdownPipe],
  templateUrl: './note-editor.component.html'
})
export class NoteEditorComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() content: string = '';
  @Input() title: string = '';
  @Input() hasUnsavedChanges: boolean = false;
  @Input() isDarkMode: boolean = false;
  @Input() isSaving: boolean = false;

  @Output() contentChange = new EventEmitter<string>();
  @Output() titleChange = new EventEmitter<string>();
  @Output() savePage = new EventEmitter<void>();
  @Output() autoSave = new EventEmitter<void>();
  @Output() uploadImage = new EventEmitter<{ file: File; callback: (markdown: string) => void }>();

  @ViewChild('editorContainer', { static: true }) editorContainer!: ElementRef;
  @ViewChild('previewContainer') previewContainer?: ElementRef;

  private view?: EditorView;
  private destroy$ = new Subject<void>();
  private changeSubject = new Subject<string>();
  private autoSaveSubject = new Subject<void>();

  // Editor Configs persistidos localmente
  editorMode = signal<'edit' | 'preview' | 'split'>('edit');
  isFullscreen = signal<boolean>(false);
  isAutoSaveEnabled = signal<boolean>(true);
  isUploadingImage = signal<boolean>(false);

  private scrollSource: 'editor' | 'preview' | null = null;
  private isUpdatingFromModel = false;

  constructor() {
    this.initializeConfig();

    // Sincronizar modificações do editor com debounce
    this.changeSubject.pipe(
      debounceTime(50),
      takeUntil(this.destroy$)
    ).subscribe((newVal) => {
      this.contentChange.emit(newVal);
      
      if (this.isAutoSaveEnabled()) {
        this.autoSaveSubject.next();
      }
    });

    // AutoSave debounced em 2 segundos
    this.autoSaveSubject.pipe(
      debounceTime(2000),
      takeUntil(this.destroy$)
    ).subscribe(() => {
      if (this.isAutoSaveEnabled()) {
        this.autoSave.emit();
      }
    });
  }

  private initializeConfig(): void {
    if (typeof window !== 'undefined') {
      const savedMode = localStorage.getItem('noteEditorMode') as 'edit' | 'preview' | 'split';
      if (savedMode) this.editorMode.set(savedMode);

      const savedAutoSave = localStorage.getItem('noteAutoSave');
      if (savedAutoSave) this.isAutoSaveEnabled.set(savedAutoSave === 'true');
    }
  }

  ngAfterViewInit(): void {
    this.initializeCodeMirror();
  }

  ngOnChanges(changes: SimpleChanges): void {
    // Re-inicializa o editor se o tema mudar
    if (changes['isDarkMode'] && !changes['isDarkMode'].firstChange) {
      this.initializeCodeMirror();
    }

    // Sincroniza o conteúdo quando atualizado externamente (nova nota carregada)
    if (changes['content']) {
      const newContent = changes['content'].currentValue || '';
      if (this.view && newContent !== this.view.state.doc.toString()) {
        this.isUpdatingFromModel = true;
        this.view.dispatch({
          changes: { from: 0, to: this.view.state.doc.length, insert: newContent }
        });
        this.isUpdatingFromModel = false;
      }
    }
  }

  ngOnDestroy(): void {
    if (this.view) {
      this.view.destroy();
    }
    this.destroy$.next();
    this.destroy$.complete();
  }

  setEditorMode(mode: 'edit' | 'preview' | 'split'): void {
    this.editorMode.set(mode);
    if (typeof window !== 'undefined') {
      localStorage.setItem('noteEditorMode', mode);
    }
  }

  toggleAutoSave(): void {
    this.isAutoSaveEnabled.update(val => !val);
    if (typeof window !== 'undefined') {
      localStorage.setItem('noteAutoSave', this.isAutoSaveEnabled().toString());
    }
  }

  private initializeCodeMirror(): void {
    if (this.view) {
      this.view.destroy();
    }

    const isDark = this.isDarkMode;

    // Custom Highlight Styles correspondentes
    const customHighlightStyle = HighlightStyle.define([
      { tag: t.link, color: isDark ? '#61afef' : '#0969da', textDecoration: 'underline' },
      { tag: t.url, color: isDark ? '#abb2bf' : '#57606a', opacity: 0.7 },
      { tag: t.heading1, fontWeight: 'bold', fontSize: '1.4em', color: isDark ? '#e06c75' : '#cf222e' },
      { tag: t.heading2, fontWeight: 'bold', fontSize: '1.2em', color: isDark ? '#d19a66' : '#953800' },
      { tag: t.strikethrough, textDecoration: 'line-through' },
      { tag: t.meta, color: isDark ? '#c678dd' : '#8250df' },
      { tag: t.keyword, color: isDark ? '#c678dd' : '#d73a49' },
      { tag: t.operator, color: isDark ? '#56b6c2' : '#005cc5' },
      { tag: t.string, color: isDark ? '#98c379' : '#032f62' },
      { tag: t.number, color: isDark ? '#d19a66' : '#005cc5' },
      { tag: t.variableName, color: isDark ? '#e06c75' : '#24292e' },
      { tag: t.comment, color: isDark ? '#5c6370' : '#6a737d', fontStyle: 'italic' },
      { tag: t.function(t.variableName), color: isDark ? '#61afef' : '#6f42c1' },
    ]);

    const startState = EditorState.create({
      doc: this.content,
      extensions: [
        history(),
        keymap.of([
          { key: 'Mod-b', run: () => { this.insertBold(); return true; } },
          { key: 'Mod-i', run: () => { this.insertItalic(); return true; } },
          { key: 'Mod-k', run: () => { this.insertLink(); return true; } },
          { key: 'Mod-1', run: () => { this.insertH1(); return true; } },
          { key: 'Mod-2', run: () => { this.insertH2(); return true; } },
          { key: 'Mod-3', run: () => { this.insertH3(); return true; } },
          { key: 'Mod-l', run: () => { this.insertList(); return true; } },
          ...defaultKeymap,
          ...historyKeymap,
        ]),
        markdown({
          base: commonmarkLanguage,
          addKeymap: true
        }),
        syntaxHighlighting(customHighlightStyle),
        isDark ? oneDark : [],
        highlightActiveLine(),
        scrollPastEnd(),
        EditorView.lineWrapping,
        EditorView.theme({
          '&': {
            height: '100%',
            fontSize: '16px',
            backgroundColor: 'transparent !important',
          },
          '&.cm-focused': {
            outline: 'none',
          },
          '.cm-content': {
            padding: '20px',
            fontFamily: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Monaco, Consolas, monospace',
          },
          '.cm-scroller': {
            lineHeight: '1.6',
            backgroundColor: 'transparent !important',
          },
          '.cm-gutters': {
            backgroundColor: 'transparent !important',
            border: 'none',
            color: isDark ? '#4b5263' : '#9ca3af',
          },
          '.cm-activeLine': {
            backgroundColor: isDark ? 'rgba(255, 255, 255, 0.05) !important' : 'rgba(0, 0, 0, 0.03) !important',
          },
          '.cm-activeLineGutter': {
            backgroundColor: 'transparent !important',
            color: isDark ? '#e06c75' : '#cf222e',
          },
          '.cm-selectionBackground, .cm-content ::selection': {
            backgroundColor: isDark ? 'rgba(255, 255, 255, 0.2) !important' : 'rgba(0, 0, 0, 0.1) !important',
          }
        }, { dark: isDark }),
        EditorView.updateListener.of((update) => {
          if (update.docChanged && !this.isUpdatingFromModel) {
            this.changeSubject.next(update.state.doc.toString());
          }
        }),
        EditorView.domEventHandlers({
          scroll: () => {
            if (this.editorMode() === 'split') {
              this.syncScroll('editor');
            }
          },
          paste: (event) => {
            this.handlePaste(event);
          }
        })
      ]
    });

    this.view = new EditorView({
      state: startState,
      parent: this.editorContainer.nativeElement
    });

    setTimeout(() => this.view?.focus(), 50);
  }

  // Lógica de Sincronia de Scroll Bidirecional
  syncScroll(source: 'editor' | 'preview'): void {
    if (this.editorMode() !== 'split' || !this.previewContainer || !this.view) return;

    if (this.scrollSource && this.scrollSource !== source) {
      this.scrollSource = null;
      return;
    }

    this.scrollSource = source;

    const editorScrollDOM = this.view.scrollDOM;
    const previewDOM = this.previewContainer.nativeElement;

    const editorScrollableHeight = this.view.contentHeight - editorScrollDOM.clientHeight;
    const previewScrollableHeight = previewDOM.scrollHeight - previewDOM.clientHeight;

    if (source === 'editor') {
      const scrollPercentage = editorScrollDOM.scrollTop / (editorScrollableHeight || 1);
      previewDOM.scrollTop = scrollPercentage * previewScrollableHeight;
    } else {
      const scrollPercentage = previewDOM.scrollTop / (previewScrollableHeight || 1);
      editorScrollDOM.scrollTop = scrollPercentage * editorScrollableHeight;
    }

    setTimeout(() => {
      if (this.scrollSource === source) {
        this.scrollSource = null;
      }
    }, 50);
  }

  onPreviewScroll(): void {
    this.syncScroll('preview');
  }

  // Clipboard Paste de Imagens
  private handlePaste(e: ClipboardEvent): void {
    const items = e.clipboardData?.items;
    if (!items) return;

    let imageFile: File | null = null;
    for (const item of Array.from(items)) {
      if (item.kind === 'file' && item.type.startsWith('image/')) {
        imageFile = item.getAsFile();
        break;
      }
    }

    if (!imageFile) return;

    e.preventDefault();
    if (this.isUploadingImage()) return;

    this.isUploadingImage.set(true);

    this.uploadImage.emit({
      file: imageFile,
      callback: (markdown: string) => {
        this.isUploadingImage.set(false);
        this.insertTextAtCursor(markdown, '');
      }
    });
  }

  // Ponte de Comandos CodeMirror
  insertTextAtCursor(beforeText: string, afterText: string = '', selectText: boolean = false): void {
    if (!this.view) return;

    const view = this.view;
    const { state, dispatch } = view;

    const changes = state.changeByRange((range) => {
      const selectedText = state.sliceDoc(range.from, range.to);
      const insertion = selectText && selectedText
        ? beforeText + selectedText + afterText
        : beforeText + afterText;

      return {
        range: EditorSelection.cursor(range.from + beforeText.length + (selectText && selectedText ? selectedText.length : 0)),
        changes: { from: range.from, to: range.to, insert: insertion }
      };
    });

    dispatch(state.update(changes, { scrollIntoView: true, userEvent: 'input' }));
    view.focus();
  }

  insertBold = () => this.insertTextAtCursor('**', '**', true);
  insertItalic = () => this.insertTextAtCursor('*', '*', true);
  insertH1 = () => this.insertTextAtCursor('# ', '');
  insertH2 = () => this.insertTextAtCursor('## ', '');
  insertH3 = () => this.insertTextAtCursor('### ', '');
  insertCode = () => this.insertTextAtCursor('`', '`', true);
  insertQuote = () => this.insertTextAtCursor('> ', '');
  insertList = () => this.insertTextAtCursor('- ', '');
  insertOrderedList = () => this.insertTextAtCursor('1. ', '');
  insertLink = () => this.insertTextAtCursor('[', '](url)');
  insertImageLink = () => this.insertTextAtCursor('![Alt text](', ')');

  undo = () => this.view && cmUndo(this.view);
  redo = () => this.view && cmRedo(this.view);

  // Zoom da imagem no visualizador da direita
  handlePreviewClick(event: MouseEvent): void {
    const target = event.target as HTMLElement;
    const imgContainer = target.closest('.markdown-img-container') as HTMLElement;
    if (imgContainer) {
      const src = imgContainer.getAttribute('data-image-src');
      const alt = imgContainer.getAttribute('data-image-alt');
      if (src && window.openImageModal) {
        window.openImageModal(src, alt || '');
      }
    }
  }
}

<div
  class="transition-all duration-300 opacity-100 translate-y-0 w-full"
  [ngClass]="{
    'fixed inset-0 z-50 bg-background': isFullscreen(),
    'max-w-7xl mx-auto p-4 md:p-8': !isFullscreen()
  }"
>
  <div class="h-full flex flex-col">
    <!-- Header de Input de Título -->
    <div class="mb-4">
      <input
        [ngModel]="title"
        (ngModelChange)="titleChange.emit($event)"
        type="text"
        placeholder="Título da entrada..."
        class="w-full text-2xl md:text-4xl font-bold bg-transparent border-none focus:outline-none placeholder-muted-foreground text-foreground px-0 focus-visible:ring-0 cursor-text"
      />
    </div>

    <!-- Barra de Ferramentas de Configuração -->
    <div class="flex flex-wrap items-center gap-2 mb-3 p-2 border border-border/80 rounded-lg bg-card shadow-sm text-xs select-none">
      <button
        type="button"
        (click)="setEditorMode('edit')"
        class="h-8 rounded px-3 flex items-center gap-1.5 font-semibold cursor-pointer transition-colors"
        [ngClass]="{
          'bg-primary text-primary-foreground': editorMode() === 'edit',
          'hover:bg-primary/10 text-foreground': editorMode() !== 'edit'
        }"
      >
        <i class="pi pi-pencil"></i>
        <span>Editor</span>
      </button>

      <button
        type="button"
        (click)="setEditorMode('preview')"
        class="h-8 rounded px-3 flex items-center gap-1.5 font-semibold cursor-pointer transition-colors"
        [ngClass]="{
          'bg-primary text-primary-foreground': editorMode() === 'preview',
          'hover:bg-primary/10 text-foreground': editorMode() !== 'preview'
        }"
      >
        <i class="pi pi-eye-slash"></i>
        <span>Preview</span>
      </button>

      <button
        type="button"
        (click)="setEditorMode('split')"
        class="h-8 rounded px-3 flex items-center gap-1.5 font-semibold cursor-pointer transition-colors"
        [ngClass]="{
          'bg-primary text-primary-foreground': editorMode() === 'split',
          'hover:bg-primary/10 text-foreground': editorMode() !== 'split'
        }"
      >
        <i class="pi pi-eye"></i>
        <span>Split</span>
      </button>

      <div class="ml-auto flex items-center gap-4 animate-fade-in">
        <!-- Status de Salvamento -->
        <span class="text-xs text-muted-foreground flex items-center gap-2">
          @if (isSaving) {
            <span class="w-2 h-2 rounded-full bg-yellow-500 animate-pulse"></span>
            <span>Salvando...</span>
          } @else if (hasUnsavedChanges) {
            <span class="w-2 h-2 rounded-full bg-zinc-500"></span>
            <span>Editando...</span>
          } @else {
            <span class="w-2 h-2 rounded-full bg-emerald-500"></span>
            <span>Salvo</span>
          }
        </span>

        <!-- Botão Auto-Save -->
        <button
          type="button"
          (click)="toggleAutoSave()"
          class="h-8 rounded px-3 font-semibold flex items-center gap-1.5 cursor-pointer border border-border bg-card transition-colors hover:bg-primary/10"
        >
          <i class="pi pi-save"></i>
          <span>Auto-Save: {{ isAutoSaveEnabled() ? 'ON' : 'OFF' }}</span>
        </button>

        <!-- Botão Salvar Manual (se Auto-Save desativado) -->
        @if (!isAutoSaveEnabled() && hasUnsavedChanges) {
          <button
            type="button"
            (click)="savePage.emit()"
            class="h-8 rounded px-3 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold flex items-center gap-1.5 cursor-pointer shadow-sm animate-fade-in"
          >
            <i class="pi pi-save"></i>
            <span>Salvar</span>
          </button>
        }

        <!-- Toggle Fullscreen -->
        <button
          type="button"
          (click)="isFullscreen.update(v => !v)"
          class="h-8 rounded px-3 font-semibold flex items-center gap-1.5 cursor-pointer border border-border bg-card transition-colors hover:bg-primary/10"
        >
          <i [class]="isFullscreen() ? 'pi pi-window-minimize' : 'pi pi-window-maximize'"></i>
          <span>{{ isFullscreen() ? 'Sair' : 'Fullscreen' }}</span>
        </button>
      </div>
    </div>

    <!-- Barra de Atalhos Rápidos (Markdown Formatting) -->
    @if (editorMode() === 'edit' || editorMode() === 'split') {
      <div class="flex flex-wrap items-center gap-1 p-1.5 mb-2 border border-border/80 rounded-lg bg-card/50 shadow-sm select-none">
        <button type="button" (click)="insertBold()" class="h-7 w-8 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground" title="Bold (Ctrl+B)">
          <i class="pi pi-bold text-xs"></i>
        </button>
        <button type="button" (click)="insertItalic()" class="h-7 w-8 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground" title="Italic (Ctrl+I)">
          <i class="pi pi-italic text-xs"></i>
        </button>

        <span class="w-px h-5 bg-border mx-1"></span>

        <button type="button" (click)="insertH1()" class="h-7 px-2 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground font-bold text-xs" title="H1">H1</button>
        <button type="button" (click)="insertH2()" class="h-7 px-2 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground font-bold text-xs" title="H2">H2</button>
        <button type="button" (click)="insertH3()" class="h-7 px-2 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground font-bold text-xs" title="H3">H3</button>

        <span class="w-px h-5 bg-border mx-1"></span>

        <button type="button" (click)="insertList()" class="h-7 w-8 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground" title="Lista Comum">
          <i class="pi pi-list text-xs"></i>
        </button>
        <button type="button" (click)="insertOrderedList()" class="h-7 w-8 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground" title="Lista Numerada">
          <i class="pi pi-sort-numeric-down text-xs"></i>
        </button>

        <span class="w-px h-5 bg-border mx-1"></span>

        <button type="button" (click)="insertQuote()" class="h-7 w-8 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground" title="Citação">
          <i class="pi pi-comment text-xs"></i>
        </button>
        <button type="button" (click)="insertCode()" class="h-7 w-8 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground" title="Código Inline">
          <i class="pi pi-code text-xs"></i>
        </button>
        <button type="button" (click)="insertLink()" class="h-7 w-8 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground" title="Link (Ctrl+K)">
          <i class="pi pi-link text-xs"></i>
        </button>
        <button type="button" (click)="insertImageLink()" class="h-7 w-8 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground" title="Marcador de Imagem">
          <i class="pi pi-image text-xs"></i>
        </button>
        
        <div class="ml-auto flex gap-1">
          <button type="button" (click)="undo()" class="h-7 w-8 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground" title="Desfazer">
            <i class="pi pi-undo text-xs"></i>
          </button>
          <button type="button" (click)="redo()" class="h-7 w-8 rounded hover:bg-primary/10 flex items-center justify-center cursor-pointer text-foreground" title="Refazer">
            <i class="pi pi-refresh text-xs"></i>
          </button>
        </div>
      </div>
    }

    <!-- Área de Exibição / Edição -->
    <div
      class="border border-border/80 rounded-lg overflow-hidden flex bg-card shadow-inner"
      [ngClass]="{
        'h-[calc(100vh-270px)]': isFullscreen(),
        'h-[calc(100vh-320px)] min-h-[580px]': !isFullscreen()
      }"
    >
      <!-- Container do CodeMirror (Editor) -->
      <div
        #editorContainer
        class="flex-1 bg-background relative overflow-hidden"
        [ngClass]="{
          'hidden': editorMode() === 'preview',
          'block': editorMode() !== 'preview'
        }"
      ></div>

      <!-- Divisor Vertical no modo Split -->
      @if (editorMode() === 'split') {
        <div class="w-px bg-border/80 flex-shrink-0"></div>
      }

      <!-- Container do Preview (Visualizador) -->
      <div
        #previewContainer
        (scroll)="onPreviewScroll()"
        class="flex-1 bg-background overflow-y-auto relative p-6 prose prose-neutral dark:prose-invert max-w-none focus:outline-none"
        [ngClass]="{
          'hidden': editorMode() === 'edit',
          'block': editorMode() !== 'edit',
          'prose-sm': editorMode() === 'split',
          'prose-base': editorMode() !== 'split'
        }"
        [innerHTML]="content | markdown"
        (click)="handlePreviewClick($event)"
      ></div>
    </div>
  </div>
</div>
